// config.js
module.exports = {
  WORDPRESS_API_URL: null,
  WORDPRESS_USERNAME: null,
  WORDPRESS_APP_PASSWORD: null,
  OPENAI_API_KEY: null,
  GOOGLE_VISION_CREDENTIALS: null,
  GOOGLE_DOCS_CREDENTIALS: null
};