apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: appraisals-backend
  namespace: civil-forge-403609
spec:
  template:
    spec:
      containers:
        - image: gcr.io/civil-forge-403609/appraisals-backend
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_CLOUD_PROJECT_ID
              value: civil-forge-403609
            - name: CORS_ALLOWED_ORIGINS
              value: "https://appraisily.com,https://app.appraisily.com,https://dev.appraisily.com"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          # Service account with access to Secret Manager
          serviceAccountName: appraisals-backend-sa
      # Opcional: Añadir configuración adicional como recursos, limites, etc.
